#pragma once
class SwapChain;
class DeviceContext;
class VertexBuffer;
class VertexShader;
class PixelShader;
class ConstantBuffer;
class IndexBuffer;
class RenderingSystem;
class GraphicsEngine;
class Resource;
class ResourceManager;
class Texture;
class TextureManager;